# Generated by Django 6.0.2 on 2026-03-01 01:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chopeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('GELO', 'A Gelo'), ('ELETRICA', 'Elétrica')], max_length=50)),
                ('status', models.CharField(choices=[('GALPAO', 'No Galpão'), ('CLIENTE', 'Com Cliente'), ('MANUTENCAO', 'Manutenção')], default='GALPAO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('endereco', models.TextField(help_text='Endereço em Barra Velha')),
                ('ponto_referencia', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('litragem', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
